### ISSUE TITLE
null string fields not handled properly by immutable models

### ISSUE THREAD

**Issue by nhammond** [StanfordBioinformatics/xppf#2]
In a model with a required models.CharFIeld, omitting that field from the JSON used to initialize the model does not cause an error. Later calling to_obj on that model raises an error.

Reproduction steps:
Edit analyses.test_models, delete the ‘requester’ field in file_import_request_obj
Then run test_models.TestModels.testFileImportRecord

*** UniqueIdMismatchError: The _id 3a713b852394f366ad67a9691203126516a824e7d1018cce1c3f5c1b4a6457d6 is out of sync with the hash of contents {'requester': u'', '_id': '3a713b852394f366ad67a9691203126516a824e7d1018cce1c3f5c1b4a6457d6', 'file': {'_id': 'baafd857fda46c21f61a5d8e99e02b55b61f4fb26f6fd4a435f242107d65e835', 'hash_value': u'1234asfd', 'hash_function': u'md5'}, 'import_comments': u'Notes about the source of this file...'} on model <class 'analyses.models.FileImportRecord'>
(Pdb) file_import_record.to_json()

**Comment by nhammond** [comment]
Similar problem for empty lists. For example, with the helloworld example, error occurs when including the setting "input_bindings": []
The error is resolved when 'input_ports' is deleted.

{
  "analysis_definitions": [
    {
      "step_template": {
        "environment": {
          "docker_image": "ubuntu"
        }, 
        "input_ports": [
          {
            "file_path": "hello.txt"
          }, 
          {
            "file_path": "world.txt"
          }
        ], 
        "command": "cat hello.txt world.txt > hello_world.txt", 
        "output_ports": [
          {
            "file_path": "hello_world.txt"
          }
        ]
      }, 
      "input_bindings": [
        {
          "input_port": {
            "file_path": "world.txt"
          }, 
          "data_object": {
            "output_port": {
              "file_path": "world.txt"
            }, 
            "analysis_definition": {
              "step_template": {
                "environment": {
                  "docker_image": "ubuntu"
                }, 
                "command": "echo world > world.txt", 
                "output_ports": [
                  {
                    "file_path": "world.txt"
                  }
                ]
              }, 
              "input_bindings": []
            }
          }
        }
      ]
    }
  ], 
  "requester": "someone@example.net"
}

ERROR: testHelloWorld (xppf.server.analyses.test.test_models.TestModels)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nhammond/repos/xppf/xppf/server/analyses/test/test_models.py", line 357, in testHelloWorld
    self.roundTripJson(analysis_request)
  File "/Users/nhammond/repos/xppf/xppf/server/analyses/test/test_models.py", line 363, in roundTripJson
    model = cls.create(model.to_json())
  File "/Users/nhammond/repos/xppf/xppf/server/immutable/models.py", line 27, in to_json
    obj = self.to_obj()
  File "/Users/nhammond/repos/xppf/xppf/server/immutable/models.py", line 330, in to_obj
    obj = super(ImmutableModel, self).to_obj()
  File "/Users/nhammond/repos/xppf/xppf/server/immutable/models.py", line 32, in to_obj
    return model._get_fields_as_obj()
  File "/Users/nhammond/repos/xppf/xppf/server/immutable/models.py", line 221, in _get_fields_as_obj
    field_obj = self._get_field_as_obj(field)
  File "/Users/nhammond/repos/xppf/xppf/server/immutable/models.py", line 232, in _get_field_as_obj
    return self._get_many_to_many_field_as_obj(field)
  File "/Users/nhammond/repos/xppf/xppf/server/immutable/models.py", line 265, in _get_many_to_many_field_as_obj
    related_model_obj.append(model.to_obj())
  File "/Users/nhammond/repos/xppf/xppf/server/immutable/models.py", line 330, in to_obj
    obj = super(ImmutableModel, self).to_obj()
  File "/Users/nhammond/repos/xppf/xppf/server/immutable/models.py", line 32, in to_obj
    return model._get_fields_as_obj()
  File "/Users/nhammond/repos/xppf/xppf/server/immutable/models.py", line 221, in _get_fields_as_obj
    field_obj = self._get_field_as_obj(field)
  File "/Users/nhammond/repos/xppf/xppf/server/immutable/models.py", line 232, in _get_field_as_obj
    return self._get_many_to_many_field_as_obj(field)
  File "/Users/nhammond/repos/xppf/xppf/server/immutable/models.py", line 265, in _get_many_to_many_field_as_obj
    related_model_obj.append(model.to_obj())
  File "/Users/nhammond/repos/xppf/xppf/server/immutable/models.py", line 330, in to_obj
    obj = super(ImmutableModel, self).to_obj()
  File "/Users/nhammond/repos/xppf/xppf/server/immutable/models.py", line 32, in to_obj
    return model._get_fields_as_obj()
  File "/Users/nhammond/repos/xppf/xppf/server/immutable/models.py", line 221, in _get_fields_as_obj
    field_obj = self._get_field_as_obj(field)
  File "/Users/nhammond/repos/xppf/xppf/server/immutable/models.py", line 234, in _get_field_as_obj
    return self._get_foreign_key_field_as_obj(field)
  File "/Users/nhammond/repos/xppf/xppf/server/immutable/models.py", line 259, in _get_foreign_key_field_as_obj
    return related_model.to_obj()
  File "/Users/nhammond/repos/xppf/xppf/server/immutable/models.py", line 330, in to_obj
    obj = super(ImmutableModel, self).to_obj()
  File "/Users/nhammond/repos/xppf/xppf/server/immutable/models.py", line 32, in to_obj
    return model._get_fields_as_obj()
  File "/Users/nhammond/repos/xppf/xppf/server/immutable/models.py", line 221, in _get_fields_as_obj
    field_obj = self._get_field_as_obj(field)
  File "/Users/nhammond/repos/xppf/xppf/server/immutable/models.py", line 234, in _get_field_as_obj
    return self._get_foreign_key_field_as_obj(field)
  File "/Users/nhammond/repos/xppf/xppf/server/immutable/models.py", line 259, in _get_foreign_key_field_as_obj
    return related_model.to_obj()
  File "/Users/nhammond/repos/xppf/xppf/server/immutable/models.py", line 331, in to_obj
    self._verify_unique_id(obj)
  File "/Users/nhammond/repos/xppf/xppf/server/immutable/models.py", line 336, in _verify_unique_id
    raise UniqueIdMismatchError("The _id %s is out of sync with the hash of contents %s on model %s" %(self._id, obj, self.__class__))
UniqueIdMismatchError: The _id c20f0f251531bcff890e2a7cf1e68fb4f33f4d622745f5a3d240b6f8c76a674d is out of sync with the hash of contents {'step_template': {'environment': {'_id': u'22cbbe3c49447f8759c09749699b0ecac47abbf45a5f695f61d59025dd46e6bb', 'docker_image': u'ubuntu'}, '_id': u'870ad33b64b649862c1d7423df8dda849cb2aced575679cf03fe68a29eac03c8', 'command': u'echo world > world.txt', 'output_ports': [{'_id': u'fe16cfe91055d39b120d7a55f9e2b286d21efc24b1dc881402ffa2573e6cf972', 'file_path': u'world.txt'}]}, '_id': u'c20f0f251531bcff890e2a7cf1e68fb4f33f4d622745f5a3d240b6f8c76a674d'} on model <class 'analyses.models.AnalysisDefinition'>

**Comment by nhammond** [comment]
Resolved. master.immutable.helpers.IdCalculator now always excludes Null and [] values.
